# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [3]:
# Exercise 1
import numpy as np
number = np.arange(1,11)
number

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [7]:
# Exercise 2
array = np.zeros((3,3))
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [9]:
# Exercise 3
array = np.linspace(0,5,10)
array

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [5]:
# Exercise 4
matrix = np.eye(5)
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [23]:
# Exercise 5
matrix = np.random.rand(4,4)
matrix

array([[0.93593149, 0.22694402, 0.86580817, 0.56556453],
       [0.40000036, 0.63958284, 0.65634323, 0.38851869],
       [0.8981595 , 0.20752177, 0.10153259, 0.57932118],
       [0.4090416 , 0.04684559, 0.29488173, 0.90615793]])


---

### Exercise 6:
Find the shape of a NumPy array.


In [25]:
# Exercise 6
print(number.shape)

(10,)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [9]:
# Exercise 7
matrix = np.arange(16).reshape(4, 4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [35]:
# Exercise 8
print(number.dtype)

int32



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [11]:
# Exercise 9
array = np.arange(1,101)
even_numbers = array[array % 2 == 0]
print(even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [27]:
# Exercise 10
matrix = np.random.randint(10, 50, size = (6,6))
matrix

array([[48, 23, 13, 36, 11, 15],
       [24, 40, 39, 29, 32, 33],
       [25, 31, 34, 38, 37, 35],
       [37, 22, 10, 47, 42, 15],
       [12, 14, 27, 24, 10, 22],
       [13, 36, 26, 47, 33, 41]])


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [29]:
# Exercise 11
submatrix = matrix[1:4, 2:5]
submatrix

array([[39, 29, 32],
       [34, 38, 37],
       [10, 47, 42]])


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [33]:
# Exercise 12
np.sum(matrix)

1021


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [41]:
# Exercise 13
print("Mean of a Numpy array is:", np.mean(matrix))
print("Median of a Numpy array is:", np.median(matrix))
print("Standard deviation of a Numpy array is:", np.std(matrix))

Mean of a Numpy array is: 28.36111111111111
Median of a Numpy array is: 30.0
Standard deviation of a Numpy array is: 11.326352697673633



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [43]:
# Exercise 14
print("Min of a Numpy array is:", np.min(matrix))
print("Max of a Numpy array is:", np.max(matrix))

Min of a Numpy array is: 10
Max of a Numpy array is: 48



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [49]:
# Exercise 15
rand_integer = np.random.randint(0, 50, 20)
max_index = np.argmax(rand_integer)
print(rand_integer)
max_index

[39 11 44 45 21 35  7 14 34 26 23 18  6 30  3  3 32 47 48 49]


19


---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [59]:
# Exercise 16
rand_integer = np.random.randint(0, 50, 20)
reverse_element = rand_integer[::-1]
print(rand_integer)
print("reverse elements:", reverse_element)

[49 37 37 49 20 19 13  5 40 37  3 44  5  0 48 23 24 38 11 20]
reverse elements: [20 11 38 24 23 48  0  5 44  3 37 40  5 13 19 20 49 37 37 49]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [69]:
# Exercise 17
matrix1 = np.random.randint(1, 10, (3, 3))
matrix2 = np.random.randint(1, 10, (3, 3))
element_wise = matrix1 * matrix2
print(matrix1)
print("============")
print(matrix2)
print("============")
print(element_wise)

[[5 2 2]
 [4 8 3]
 [8 2 4]]
[[7 7 9]
 [4 9 1]
 [9 3 8]]
[[35 14 18]
 [16 72  3]
 [72  6 32]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [71]:
# Exercise 18
matrix = np.array([1, 2, 3])
diag_matrix = np.diag(matrix)
diag_matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [73]:
# Exercise 19
matrix1 = np.array([[1, 1], [2, 2]])
matrix2 = np.array([[3, 3], [4, 4]])
matrix_dot = np.dot(matrix1, matrix2)
matrix_dot

array([[ 7,  7],
       [14, 14]])


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [75]:
# Exercise 20
flatten_matrix = matrix1.flatten()
flatten_matrix

array([1, 1, 2, 2])


---

### Exercise 21:
Stack two NumPy arrays vertically.


In [77]:
# Exercise 21
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
vertically_stack = np.vstack((a, b))
print(vertically_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [79]:
# Exercise 22
Horizontally_stack = np.hstack((a, b))
print (Horizontally_stack)

[[1 2 5 6]
 [3 4 7 8]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [83]:
# Exercise 23
arr = np.array([1, 2, 3, 4, 5, 6])
subarrays = np.split(arr, 3) 

print(subarrays)

[array([1, 2]), array([3, 4]), array([5, 6])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [87]:
# Exercise 24
arr = np.random.rand(3,3)
round_2dec = np.round(arr, 2)
round_2dec

array([[0.17, 0.35, 0.89],
       [0.67, 0.91, 0.07],
       [0.63, 0.14, 0.98]])


---

### Exercise 25:
Find the unique elements of a NumPy array.


In [93]:
# Exercise 25
arr = np.array([1,1,3,4,4,4,2])
unique_element = np.unique(arr)
unique_element

array([1, 2, 3, 4])


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [95]:
# Exercise 26
arr = np.array([1, 2, 3, 4, 5])
arr[arr < 3] = 3
arr

array([3, 3, 3, 4, 5])


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [97]:
# Exercise 27
arr = np.array([1, 2, 3])
sum_cum_el= np.cumsum(arr)
sum_cum_el

array([1, 3, 6])


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [99]:
# Exercise 28
arr = np.array([0, 1, 0, 0, 5])
non_zero = np.count_nonzero(arr)
non_zero

2


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [103]:
# Exercise 29
rand_integer = np.random.randint(0, 50, 10)
sorted_int = np.sort(rand_integer)
sorted_int

array([ 2,  5,  7,  9, 20, 31, 34, 36, 41, 44])


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [105]:
# Exercise 30
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
row_sum = np.sum(matrix, axis=1)
col_sum = np.sum(matrix, axis=0)

print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [107]:
# Exercise 31
arr = np.random.rand(3, 3)
norma = (arr - arr.min()) / (arr.max() - arr.min())
norma

array([[0.85899096, 0.69447455, 0.46973041],
       [0.45955654, 0.        , 0.9417373 ],
       [1.        , 0.38184522, 0.51610718]])


---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [109]:
# Exercise 32
a = np.array([1, 2])
b = np.array([3, 4])
dot = np.dot(a, b)
dot

11


---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [111]:
# Exercise 33
arr = np.array([[1, 2], [3, 4]])
arr = np.trace(arr)
arr

5


---

### Exercise 34:
Create a 2D array and swap two rows.


In [115]:
# Exercise 34
arr = np.array([[1, 2], [3, 4]])
arr[[0, 1]] = arr[[1, 0]]
arr

array([[3, 4],
       [1, 2]])


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [117]:
# Exercise 35
arr = np.array([1, 2, 3])
col_vector = arr[:, np.newaxis]
col_vector

array([[1],
       [2],
       [3]])


---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [123]:
# Exercise 36
matrix = np.array([
    [1, 2, 1],
    [0, 4, 5],
    [1, 0, 6]
])
det = np.linalg.det(matrix)
det

29.99999999999999


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [127]:
# Exercise 37
matrix = np.array([[4, 2], [1, 3]])
eigvalue, eigvector = np.linalg.eig(matrix)
print(eigvalue, eigvector)

[5. 2.] [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [133]:
# Exercise 38
#Solve: x + 2y = 5, 2x + 3y = 15
a = np.array([[1, 2], [3, 4]])
b = np.array([4, 8])
linear_eq = np.linalg.solve(a, b)
linear_eq

array([0., 2.])


---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [135]:
# Exercise 39
arr = np.array([1, 2, 3])
gaus_noise = np.random.normal(0, 1, arr.shape)
result = arr + gaus_noise
result

array([0.72627742, 1.69795762, 3.82838305])


---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [139]:
# Exercise 40
matrix = np.random.randint(1, 10, (4, 4))
diag_extr = np.diag(matrix)
diag_extr

array([2, 2, 6, 9])


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [141]:
# Exercise 41
arr = np.random.rand(100) * 100
clipped = np.clip(arr, 10, 50)
clipped

array([10.        , 10.        , 50.        , 10.44999722, 50.        ,
       21.51639863, 50.        , 20.78406708, 10.        , 10.        ,
       15.13391964, 10.        , 10.        , 14.16311937, 36.13222394,
       50.        , 10.        , 34.82968339, 42.87756604, 40.76465   ,
       50.        , 44.83547989, 10.        , 50.        , 50.        ,
       38.05591179, 40.37170028, 30.01776114, 40.45761469, 50.        ,
       27.21909933, 50.        , 50.        , 50.        , 50.        ,
       50.        , 13.51667064, 45.81722326, 36.38410723, 10.        ,
       50.        , 11.1749848 , 11.16090816, 50.        , 50.        ,
       28.24824983, 24.81450761, 44.73684959, 50.        , 10.        ,
       37.13099609, 23.83989113, 50.        , 49.45199929, 50.        ,
       50.        , 21.98251416, 43.3112615 , 10.        , 50.        ,
       50.        , 20.32393011, 50.        , 50.        , 50.        ,
       10.        , 50.        , 50.        , 50.        , 50.  


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [143]:
# Exercise 42
arr = np.array([[1, -1], [-5, 4]])
arr[arr < 0] = 0
arr

array([[1, 0],
       [0, 4]])


---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [147]:
# Exercise 43
a = np.array([10, 20])
b = np.array([30, 40])
inner = np.inner(a, b)
outer = np.outer(a, b)
print(outer, inner)

[[300 400]
 [600 800]] 1100



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [151]:
# Exercise 44
points = np.random.rand(4, 2)
from scipy.spatial.distance import pdist, squareform
distances = squareform(pdist(points))
distances

array([[0.        , 0.51617205, 0.40743402, 0.70102838],
       [0.51617205, 0.        , 0.91662011, 0.41546371],
       [0.40743402, 0.91662011, 0.        , 1.01136306],
       [0.70102838, 0.41546371, 1.01136306, 0.        ]])


---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [155]:
# Exercise 45
arr = np.array([('Ange', 25, 1.8), ('King', 30, 2)],
                 dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])
arr

array([('Ange', 25, 1.8), ('King', 30, 2. )],
      dtype=[('name', '<U10'), ('age', '<i4'), ('height', '<f4')])


---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [165]:
# Exercise 46
matrix = np.random.randint(0, 10, (5, 5))
unique_value, count = np.unique(matrix, return_counts=True)
count

array([2, 2, 3, 3, 3, 2, 4, 4, 1, 1], dtype=int64)


---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [169]:
# Exercise 47
matrix = np.random.rand(3, 3)
mean_row = matrix.mean(axis=1, keepdims=True)
centered = matrix - mean_row
centered

array([[ 0.17343413,  0.3089645 , -0.48239864],
       [ 0.06621407,  0.17241087, -0.23862494],
       [-0.07303534,  0.44388012, -0.37084478]])


---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [171]:
# Exercise 48
arr = np.random.randint(0, 100, 10)
any_gt_50 = np.any(arr > 50)
any_gt_50

True


---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [179]:
# Exercise 49
arr = np.random.rand(10)
window_size = 3
moving_avg = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')
moving_avg

array([0.55270509, 0.66229161, 0.70012507, 0.48528254, 0.35305555,
       0.46311391, 0.62028359, 0.67975137])


---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [183]:
# Exercise 50
a = np.random.rand(10)
b = np.random.rand(10)
correl_coe = np.corrcoef(a, b)[0, 1]
correl_coe

-0.2979738256666905


---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [185]:
# Exercise 51
rad = np.array([0, np.pi/2, np.pi])
deg = np.degrees(rad)
deg

array([  0.,  90., 180.])


---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [191]:
# Exercise 52
arr = np.random.rand(10)
var = np.var(arr)
std = np.std(arr)
print(var)
print(std)

0.09499221120963112
0.30820806480303387



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [193]:
# Exercise 53
arr = np.random.rand(3, 3)
max_index_row = np.argmax(arr, axis=1)
max_index_col = np.argmax(arr, axis=0)
print(max_index_row, max_index_col)

[2 0 2] [1 1 2]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [197]:
# Exercise 54
matrix = np.array([[4, 7], [2, 6]])
inverse_mat = np.linalg.inv(matrix)
inverse_mat

array([[ 0.6, -0.7],
       [-0.2,  0.4]])


---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [201]:
# Exercise 55
arr5= np.random.rand(10)
standardized = (arr - np.mean(arr)) / np.std(arr)
standardized

array([[-2.12192492, -0.68591315,  0.76334195],
       [ 1.39848372,  0.16555731,  0.12520308],
       [-0.685592  ,  0.05474479,  0.98609923]])


---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [205]:
# Exercise 56
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
addition = x + y
subtraction = x - y
print(addition, subtraction)

[5 7 9] [-3 -3 -3]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [209]:
# Exercise 57
arr = np.random.rand(10)
max_index = np.argmax(arr)
print(arr)
print(max_index)

[0.85724029 0.06625562 0.49290879 0.67996246 0.36497658 0.31333804
 0.11610466 0.7045037  0.60658211 0.87425605]
9



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [211]:
# Exercise 58
arr = np.arange(9).reshape(3, 3)
rotated_90deg = np.rot90(arr)
rotated_90deg

array([[2, 5, 8],
       [1, 4, 7],
       [0, 3, 6]])


---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [215]:
# Exercise 59
matrix = np.array([[1, 2], [3, 4]])
frobenius_norm = np.linalg.norm(matrix)
frobenius_norm

5.477225575051661


---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [219]:
# Exercise 60
arr = np.arange(24).reshape(2, 3, 4)
subarray = arr[0, 1:3, 0:3]
subarray

array([[ 4,  5,  6],
       [ 8,  9, 10]])


---